name: Deploy to Docker Hub
on: [push]
jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: install npm modules
        run: npm i

      - name: Build application
        run: npm run build:docker
