name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: npm install

      - name: npm build
      - run: npm run build --configuration=docker
