name: Deploy to Docker
on: [push]
jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: install npm modules
        run: npm i
      - name: build
        run: npm run build
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact_app
          path: ./dist/repolist/

  create-docker:
    needs: create-artifact
    runs-on: ubuntu-latest
    steps:
      - name: get Data From Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact_app
          path: ./dist/repolist/
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag kovacszsolt/docker-registry-manager:latest
      - name: Publish the Docker image to DockerHub
        run: docker push kovacszsolt/docker-registry-manager:latest
