name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: npm install

      - name: npm build
      - run: npm run build --configuration=docker
